### ISSUE TITLE
Trojan detected?

### ISSUE THREAD

**Issue by SimonR-Nano** [angeluriot/Maze_solver#2]
https://www.virustotal.com/gui/file/996781f8e5617a5a7c9de8cc61ad72619d970b3cab71a55f80c1678475850f45/detection

**Comment by LouissXI** [comment]
Je pense que c'est une erreur des Anti-Virus. Il faut après que chacun donne son avis. Mais ça m'étonnerais énormément qu'il y est un Trojan dedans.

**Comment by Andyloris** [comment]
c'est a cause du fait qu'il n'a pas été beacoup utilisé par les utilisateurs de l'antivirus
